### ISSUE TITLE
Fast module upgrading issue

### ISSUE THREAD

**Issue by CaitSith2** [JohnTheCoolingFan/RFT-modules#1]
Found an issue with module upgrading with ctrl-click.  What happens is that everything upgrades fine goring from tier 1 to tier 4.  Once that happens, and I later get Tier 5 modules, those will NOT fast-upgrade the tier 4 modules.  I instead have to use an explicit upgrade planner to replace them.  Ditto with Tier 5 to Tier 6,  or even Tier 4 to Tier 6.

https://github.com/JohnTheCoolingFan/RFT-modules/blob/4bd827b28ad32aeafe6486ce9385790dec1a42b8/prototypes/item/merged-module.lua#L79-L80 - Should say Tier = 5

https://github.com/JohnTheCoolingFan/RFT-modules/blob/4bd827b28ad32aeafe6486ce9385790dec1a42b8/prototypes/item/merged-module.lua#L96-L97 - Should say Tier = 6

and so on and so forth for all of the Tier 5/6 modules.

**Comment by CaitSith2** [comment]
Same issue is also present in the Random Factorio Things mod as well.

**Comment by JohnTheCoolingFan** [comment]
Thanks for pointing this out! It will be fixed in the next update.
